matchnum:
    type: number
    display: Match Number
    min: 0
team:
    type: number
    display: Team Number
    min: 0
comment:
    type: textarea
    display: heck
radios:
    type: grid
    gridtype: radio
    display: raido thingy
    rows: 1
    columns: 4
    labels:
        0,0: element1
        0,1: test
        0,2: yeet
        0,3: yeet2