matchnum:
    type: number
    display: "Match Number"
team:
    type: number
    display: "Team Number"
number:
    type: number
    display: "Number"
boolean:
    type: checkbox
    display: "Boolean"
string:
    type: text
    display: "String"
points:
    type: number
    display: "points"
testthing:
    type: number
    display: "oooh fancy a test"