matchnum:
    type: number
    display: Match Number
    metatype: field
team:
    type: number
    display: Team Number
    metatype: field
number:
    type: number
    display: Number
    metatype: field
string:
    type: string
    display: epic
    metatype: field
checkgrid:
    type: grid
    display: Rocket
    gridtype: checkbox
    columns: 5
    rows: 5
    metatype: display
highest_row:
    metatype: value
    type: counter
    counting: checkgrid
    selections:
        - 0,0
        - 1,0
        - 2,0
        - 3,0
        - 4,0
lowest_row:
    metatype: value
    type: counter
    counting: checkgrid
    selections:
        - 4,0
        - 4,1
        - 4,2
        - 4,3
        - 4,4
