matchnum:
    type: number
    display: Match Number
    metatype: field
team:
    type: number
    display: Team Number
    metatype: field
number:
    type: number
    display: Number
    metatype: field
string:
    type: string
    display: epic
    metatype: field
checkgrid:
    type: grid
    display: Rocket
    gridtype: checkbox
    columns: 5
    rows: 6
    metatype: display
    skipdraw:
        - 0,2
        - 0,3
        - 1,2
        - 1,3
        - 3,0
        - 3,1
        - 3,4
        - 3,5
        - 2,2
        - 2,3
        - 4,0
        - 4,1
        - 5,0
        - 5,1
        - 4,4
        - 4,5
        - 5,4
        - 5,5
counter_test:
    metatype: value
    type: counter
    counting: checkgrid
    selections:
        - 0,2
        - 1,2
        - 4,2
        - 5,2
