page_type: form
gearheads_banner:
  type: image
  filename: gearheads.png
  position: top
matchnum:
  type: number
  display: Match Number
  position: float
  required: true
team:
  type: number
  display: Team Number
  position: float
  required: true

#auton questions
auton_cargo_upper:
  type: number
  display: "# Auton Cargo Scored Upper Hub"
auton_cargo_lower:
  type: number
  display: "# Auton Cargo Scored Lower Hub" 
auton_taxi:
  type: radio
  display: Move During Auton (Taxi)?
  options:
    - 'Yes'
    - 'No'

#teleop questions
teleop_cargo_upper:
  type: number
  display: "# Teleop Cargo Scored Upper Hub"
teleop_cargo_lower:
  type: number
  display: "# Teleop Cargo Scored Lower Hub"

#climbing questions
climbing_level:
  type: radio
  display: Climb Level
  options:
    - '0' 
    - '1'
    - '2'
    - '3'
    - '4'
climb_sucess:
  type: radio
  display: Climb Successful?
  options:
    - 'Yes'
    - 'No'

defense:
  type: radio
  display: Defense
  options:
    - 'not controllable'
    - 'poor'
    - 'pushed around'
    - 'adequate'
    - "didn't defend but looked strong"
    - 'Excellent'
extra:
  type: checkbox
  display: Extra
  options:
    - 'Very Manuverable'
    - "Brick Bot"
    - "Powerful Bot"
    - 'Damaged'
    - 'Lost Comms'
robot_stop_time:
  type: number
  display: If robot stopped, indicate for how long (seconds)

submit_button:
  type: submit
  method: post
  text: Submit