page_type: form
gearheads_banner:
  type: image
  filename: gearheads.png
  position: top
matchnum:
  type: number
  display: Match Number
  # position: float
  required: true
team:
  type: number
  display: Team Number
  # position: float
  required: true

#auton questions
auton start pos:
  type: radio
  display: "Auton start position: bump=charging station cord cover"
  options:
    - 'Bump'
    - 'Center'
    - 'No Bump'

auton station level:
  type: radio
  display: "Auton charging station dock level"
  options:
    - 'No Balancing Shown'
    - 'Docked'
    - 'Engaged (level)'
    - 'Left community'

auton first piece type:
  type: radio
  display: "Auton First Piece object"
  options:
    - 'Cone'
    - 'Cube'
    - 'None'
auton first piece:
  type: radio
  display: "Auton First Piece placement"
  options:
    - 'Missed/None'
    - 'High'
    - 'Mid'
    - 'Low'
auton second piece type:
  type: radio
  display: "Auton Second Piece object"
  options:
    - 'Cone'
    - 'Cube'
    - 'None'
auton second piece:
  type: radio
  display: "Auton Second Piece placement"
  options:
    - 'Missed/None'
    - 'High'
    - 'Mid'
    - 'Low'
auton third piece type:
  type: radio
  display: "Auton Third Piece object"
  options:
    - 'Cone'
    - 'Cube'
    - 'None'
auton third piece:
  type: radio
  display: "Auton Third Piece placement"
  options:
    - 'Missed/None'
    - 'High'
    - 'Mid'
    - 'Low'
#auton middle:
#  type: number
#  display: "# Auton placed middle node"
#auton low:
#  type: number
#  display: "# Auton placed low node"
#teleop questions
#teleop upper:
#  type: number
#  display: "# Teleop placed high node"
#teleop middle:
#  type: number
#  display: "# Teleop placed middle node"
#teleop low:
#  type: number
#  display: "# Teleop placed low node"
placeable game pieces:
  type: checkbox
  display: "What game pieces can they place"
  options:
    - 'Cones'
    - 'Cubes'

teleop strategy:
  type: textarea
  display: "What is their strategy in teleop"

#endgame questions
endgame station:
  type: radio
  display: endgame charging station level
  options:
    - 'No station'
    - 'Docked'
    - 'Engaged (level)'
    - 'Parked (in community)'

endgame strategy:
  type: radio
  options:
    - 'continue placing piece'
    - 'climb charge station'
    - 'both'

defense:
  type: textarea
  display: "What is There defense like?"
#  options:
#    - 'No Defense shown'
#    - "Can't defend at all"
#    - 'Pushes a little bit'
#    - 'Moderately slows down robots'
#    - 'Very Good defense, significantly slows robots'

broke down:
  type: textarea
  display: "Did the bot break down or stop doing offense?"

extra:
  type: checkbox
  display: Extra
  options:
    - 'Drops Pieces'
    - 'Brick Bot'
    - 'Maneuverable'
    - 'Lost Comms'
    - 'Tipped over'
    - 'Picks up from ground'

comments:
  type: textarea
  display: "Additional comments"

submit_button:
  type: submit
  method: post
  text: Submit
