weights:
  gaming: 1000

values:
  communication: {'0': -5,'1': -4, '2': -3, '3': -2, '4': -1, '5': 0, '6': 1, '7': 2, '8': 3, '9': 4, '10': 5}
  responsiveness: {'0': -5,'1': -4, '2': -3, '3': -2, '4': -1, '5': 0, '6': 1, '7': 2, '8': 3, '9': 4, '10': 5}
  team dynamics: {'0': -5,'1': -4, '2': -3, '3': -2, '4': -1, '5': 0, '6': 1, '7': 2, '8': 3, '9': 4, '10': 5}
  ability: {'0': -5,'1': -4, '2': -3, '3': -2, '4': -1, '5': 0, '6': 1, '7': 2, '8': 3, '9': 4, '10': 5}
  altercations: {"Yes": -5, "No": 5}
