page_type: form
gearheads_banner:
  type: image
  filename: gearheads.png
  position: top
team:
  type: number
  display: Team Number
  # position: float
  required: true

robolength:
  type: number
  display: "Robot Length"

robowidth:
  type: number
  display: "Robot Width"

roboweight:
  type: number
  display: "Robot Weight"

drivetrain:
  type: textarea
  display: "Drive Train"

roboconstruction:
  type: textarea
  display: "Robot construction (flimsy, solid, etc)"

wiring:
  type: radio
  display: "wiring"
  options:
    - 

"drive train: text
robot construction: flimsy solid, etc: text
organized wiring: neat, neutral, chaoctic
subsystem number: number
subsystem concern of overcomplexity: text
pit crew sie: number
point of concern: text
spare assemblies: yes/no
notable featyures: text
condition of robot: text
tipp: tes/no
addiotonal notes: text"