page_type: form
gearheads_banner:
  type: image
  filename: gearheads.png
  position: top
matchnum:
  type: number
  display: Match Number
  # position: float
  required: true
team:
  type: number
  display: Team Number
  # position: float
  required: true

robolength:
  type: float
  display: "Robot Length"

robowidth:
  type: float
  display: "Robot Width"

roboweight:
  type: float
  display: "Robot Weight"

drivetrain:
  type: textarea
  display: "Drive Train"

roboconstruction:
  type: textarea
  display: "Robot construction (flimsy, solid, etc)"

wiring:
  type: radio
  display: "wiring"
  options:
    - "neat"
    - "neutral"
    - "choaotic"

numsubsystem:
  type: number
  display: "num of subsystems"

subcomplex:
  type: textarea
  display: "concern of overcomplex subsystems?"

pitnum:
  type: number
  display: "num of pitcrew memebers"

poc:
  type: textarea
  display: "Points of concern?"

spare:
  type: radio
  display: "spare assemblies?"
  options: ["yes", "no"]

notable:
  type: textarea
  display: "notable features"

condition:
  type: textarea
  display: "condition of robot"

tippy:
  type: radio
  display: "tippy"
  options: ["yes", "no"]

additonal:
  type: textarea
  display: "comments"

submit_button:
  type: submit
  method: post
  text: Submit
