page_type: form
gearheads_banner:
  type: image
  filename: gearheads.png
  position: top
matchnum:
  type: number
  display: Match Number
  # position: float
  required: true
team:
  type: number
  display: Team Number
  # position: float
  required: true

#robolength:
#  type: float
#  display: "Robot Length"
#
#robowidth:
#  type: float
#  display: "Robot Width"
#
#roboweight:
#  type: float
#  display: "Robot Weight"

drivetrain:
  type: textarea
  display: "Drive Train"

pare:
  type: radio
  display: "spare parts?"
  options: ["yes", "no"]

start position:
  type: radio
  display: "preferred starting position in auton?"
  options: ["bump", "center", "no bump"]

notable:
  type: textarea
  display: "notable features"

autons:
  type: textarea
  display: "what autons can they run?"

goals:
  type: textarea
  display: "what are their preferred goals?"

roboconstruction:
  type: textarea
  display: "Apparent robot construction (flimsy, solid, etc)"

wiring:
  type: radio
  display: "Apparent wiring"
  options:
    - "neat"
    - "neutral"
    - "choaotic"

#numsubsystem:
#  type: number
#  display: "num of subsystems"
#
#subcomplex:
#  type: textarea
#  display: "concern of overcomplex subsystems?"

#pitnum:
#  type: number
#  display: "num of pitcrew memebers"

poc:
  type: textarea
  display: "Apparent points of concern?"

condition:
  type: textarea
  display: "condition of robot"

#tippy:
#  type: radio
#  display: "tippy"
#  options: ["yes", "no"]

additional:
  type: textarea
  display: "comments"

submit_button:
  type: submit
  method: post
  text: Submit
