weights:
  teleop upper: 1.2
  teleop middle: 1
  teleop low: 1
  auton upper: 1.2
  auton middle: 1
  auton low: 1
  robot_stop_time: -1.5


values:
  auton station level:
    'No Balancing Shown': 0
    'Docked': 8
    'Engaged (level)': 16
  placeable game pieces:
    'Cones': 0
    'Cubes': 0

  endgame station:
    'No station': 0
    'Docked': 6
    'Engaged (level)': 12

  hp comms: {'poor': -3, 'good': 3}

  # extras
  'Very Maneuverable': {'true': 3, 'false': 0}
  'Brick Bot': {'true': -35, 'false': 0}
  'Holds pieces well': {'true': 10, 'false': 0}
  'Good at defense': {'true': 4, 'false': 0}
  'Lost Comms': {'true': -5, 'false': 0}
