weights:
  teleop upper: 5
  teleop middle: 3
  teleop low: 2
  auton upper: 6
  auton middle: 4
  auton low: 3
  robot_stop_time: -0.05


values:
  auton station level:
    'No Balancing Shown': 0
    'Docked': 8
    'Engaged (level)': 14
    'Left community': 3

  placeable game pieces:
    'Cones': 0
    'Cubes': 0

  endgame station:
    'No station': 0
    'Docked': 6
    'Engaged (level)': 10
    'Parked (in community)': 3

  defense:
    'No Defense shown': 0
    "Can't defend at all": 0
    'Pushes a little bit': 2
    'Moderately slows down robots': 4
    'Very Good defense, significantly slows robots': 7

  hp comms: {'poor': -3, 'good': 3, 'neutral/no human': 0}

  # extras
  'extra_Very Maneuverable': {'true': 5, 'false': 0}
  'extra_Brick Bot': {'true': 0, 'false': 0}
  'extra_Drops Pieces': {'true': -5, 'false': 0}
  'extra_Good at defense': {'true': 4, 'false': 0}
  'extra_Lost Comms': {'true': -5, 'false': 0}
  'extra_Tipped over': {'true': -10, 'false': 0}
  'extra_Picks up from ground': {'true': 5, 'false': 0}
